### ISSUE TITLE
Colmet stopped to record data into hdf5 file with "bad heap free list"; file corrupted?

### ISSUE THREAD

**Issue by bzizou** [oar-team/colmet#1]
I noticed that my colmet was not updating the hdf5 file anymore with an arror into the log file (below).
I can reproduce the same error "bad heap free list" if I try to read data inside the hdf5 file using h5py.
# Error logged:

Traceback (most recent call last):
  File "/applis/ciment/v2/stow/x86_64/gcc_4.6.2/python_2.7.2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(_args, *_kwargs)
  File "/var/lib/colmet/colmet-0.3.0/colmet/common/backends/zeromq.py", line 48, in <lambda>
    intern_callback = lambda x: self.unpack(x, callback)
  File "/var/lib/colmet/colmet-0.3.0/colmet/common/backends/zeromq.py", line 45, in unpack
    callback(counters)
  File "/var/lib/colmet/colmet-0.3.0/colmet/collector/main.py", line 58, in collect
    self.push()
  File "/var/lib/colmet/colmet-0.3.0/colmet/collector/main.py", line 47, in push
    backend.push(self.counters_list)
  File "/var/lib/colmet/colmet-0.3.0/colmet/collector/hdf5.py", line 222, in push
    jobstat.append_stats(c_list)
  File "/var/lib/colmet/colmet-0.3.0/colmet/collector/hdf5.py", line 361, in append_stats
    self._init_job_file_if_needed(stats[0].metric_backend)
  File "/var/lib/colmet/colmet-0.3.0/colmet/collector/hdf5.py", line 332, in _init_job_file_if_needed
    if table_path not in self.job_file:
  File "/applis/ciment/v2/stow/x86_64/gcc_4.6.2/python_2.7.2/lib/python2.7/site-packages/tables-2.4.0-py2.7-linux-x86_64.egg/tables/file.py", line 1506, in __contains__
    self.getNode(path)
  File "/applis/ciment/v2/stow/x86_64/gcc_4.6.2/python_2.7.2/lib/python2.7/site-packages/tables-2.4.0-py2.7-linux-x86_64.egg/tables/file.py", line 1112, in getNode
    node = self._getNode(nodePath)
  File "/applis/ciment/v2/stow/x86_64/gcc_4.6.2/python_2.7.2/lib/python2.7/site-packages/tables-2.4.0-py2.7-linux-x86_64.egg/tables/file.py", line 1057, in _getNode
    node = self.root._g_loadChild(nodePath)
  File "/applis/ciment/v2/stow/x86_64/gcc_4.6.2/python_2.7.2/lib/python2.7/site-packages/tables-2.4.0-py2.7-linux-x86_64.egg/tables/group.py", line 1131, in _g_loadChild
    childClass = self._g_getChildLeafClass(childName, warn=True)
  File "/applis/ciment/v2/stow/x86_64/gcc_4.6.2/python_2.7.2/lib/python2.7/site-packages/tables-2.4.0-py2.7-linux-x86_64.egg/tables/group.py", line 291, in _g_getChildLeafClass
    childCID = self._g_getLChildAttr(childName, 'CLASS')
  File "hdf5Extension.pyx", line 708, in tables.hdf5Extension.Group._g_getLChildAttr (tables/hdf5Extension.c:6793)

HDF5ExtError: HDF5 error back trace

  File "H5D.c", line 334, in H5Dopen2
    not found
  File "H5Gloc.c", line 430, in H5G_loc_find
    can't find object
  File "H5Gtraverse.c", line 861, in H5G_traverse
    internal path traversal failed
  File "H5Gtraverse.c", line 596, in H5G_traverse_real
    can't look up component
  File "H5Gobj.c", line 1156, in H5G_obj_lookup
    can't locate object
  File "H5Gstab.c", line 892, in H5G_stab_lookup
    unable to protect symbol table heap
  File "H5HL.c", line 490, in H5HL_protect
    unable to load heap data block
  File "H5AC.c", line 1322, in H5AC_protect
    H5C_protect() failed.
  File "H5C.c", line 3567, in H5C_protect
    can't load entry
  File "H5C.c", line 7957, in H5C_load_entry
    unable to load entry
  File "H5HLcache.c", line 670, in H5HL_datablock_load
    unable to destroy local heap data block
  File "H5HLint.c", line 401, in H5HL_dblk_dest
    can't unpin local heap prefix
  File "H5AC.c", line 1456, in H5AC_unpin_entry
    can't unpin entry
  File "H5C.c", line 5058, in H5C_unpin_entry
    Entry isn't pinned
  File "H5HLcache.c", line 657, in H5HL_datablock_load
    can't initialize free list
  File "H5HLcache.c", line 154, in H5HL_fl_deserialize
    bad heap free list

End of HDF5 error back trace
# Code to reproduce the error, on a random job_id:
# !/bin/env python

import h5py
import numpy as np
colmetfile="/scratch/bzizou/colmet/froggy.2015-02-16.hdf5"
f = h5py.File(colmetfile, "r")
for name in f['5200156']:
    print name
# Error reproduced:

Traceback (most recent call last):
  File "./colmet_hdf5_reader.py", line 9, in <module>
    for name in f['5200156']:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/applis/site/src/h5py-2.4.0/h5py/_objects.c:2705)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/applis/site/src/h5py-2.4.0/h5py/_objects.c:2662)
  File "build/bdist.linux-x86_64/egg/h5py/_hl/group.py", line 160, in __getitem__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/applis/site/src/h5py-2.4.0/h5py/_objects.c:2705)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/applis/site/src/h5py-2.4.0/h5py/_objects.c:2662)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/applis/site/src/h5py-2.4.0/h5py/h5o.c:3756)
KeyError: 'Unable to open object (Bad heap free list)'

**Comment by bzizou** [comment]
Here: http://www.hdfgroup.org/HDF5/release/known_problems/
they talk about a " tool is being developed that can be run on a corrupted file to correct it. "

**Comment by bzizou** [comment]
Obsolete issue
