### ISSUE TITLE
Crash on "RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by bzizou** [oar-team/colmet#7]
We have frequent crashes of colmet-node, on the implementation_rapl_perfhw branch. Here's the backtrace:

```
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Gathering the metrics
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991288
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4990850
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991289
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991222
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991263
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - INFO - no taks in this cgroup
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4990583
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - INFO - no taks in this cgroup
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4990632
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148800 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148801 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148802 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 144963 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148804 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148805 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148806 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148807 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148808 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148809 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148810 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148811 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148816 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148803 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 148815 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 145018 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - Process/Task 144956 no more exists.Removing from the Job /dev/cpuset/oar/cbardel_4991293
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991224
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991287
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991285
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991295
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991282
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - INFO - no taks in this cgroup
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - DEBUG - pull job :4991225
Nov 16 12:56:00 dahu70 oar-node[1860]: 16/11/2019 12:56:00 - CRITICAL - Error not handled 'RuntimeError'
Nov 16 12:56:00 dahu70 oar-node[1860]: Traceback (most recent call last):
Nov 16 12:56:00 dahu70 oar-node[1860]:   File "/applis/site/colmet/bin/colmet-node", line 10, in <module>
Nov 16 12:56:00 dahu70 oar-node[1860]:     sys.exit(main())
Nov 16 12:56:00 dahu70 oar-node[1860]:   File "/applis/site/colmet/lib/python3.5/site-packages/colmet/node/main.py", line 236, in main
Nov 16 12:56:00 dahu70 oar-node[1860]:     Task(sys.argv[0], args).start()
Nov 16 12:56:00 dahu70 oar-node[1860]:   File "/applis/site/colmet/lib/python3.5/site-packages/colmet/node/main.py", line 73, in start
Nov 16 12:56:00 dahu70 oar-node[1860]:     self.loop()
Nov 16 12:56:00 dahu70 oar-node[1860]:   File "/applis/site/colmet/lib/python3.5/site-packages/colmet/node/main.py", line 95, in loop
Nov 16 12:56:00 dahu70 oar-node[1860]:     pulled_counters = backend.pull()
Nov 16 12:56:00 dahu70 oar-node[1860]:   File "/applis/site/colmet/lib/python3.5/site-packages/colmet/node/backends/taskstats.py", line 47, in pull
Nov 16 12:56:00 dahu70 oar-node[1860]:     for job in self.jobs.values():
Nov 16 12:56:00 dahu70 oar-node[1860]: RuntimeError: dictionary changed size during iteration
```

**Comment by lambertrocher** [comment]
inotify détecte les changements dans son propre thread, il se pourrait que des éléments soit ajoutés/retirés à self.jobs pendant la boucle for si la fonction pull est appelée exactement au moment où un job commence ou se termine ? une solution simple pourrait être de créer un copie -> list(self.jobs.values())

-------------------------------------------
def pull(self):
        for job in self.jobs.values():
            LOG.debug("pull job :" + str(job.job_id))
            job.update_stats()
        return [job.get_stats() for job in self.jobs.values()]

**Comment by bzizou** [comment]
For the moment, I made a "while [ 1 ]" loop restarting colmet-node in case of a crash
